import 'package:get/get.dart';

class LocalString extends Translations {
  @override
  // TODO: implement keys

  Map<String, Map<String, String>> get keys => {
        // english
        'en': {
          'hello': 'Hello',
          'welcome to cza exchange': 'welcome to cza exchange',
          'high level security': 'high level security',
          'seemless transactions': 'seemless transaction',
          '24/7 customer care service': '24/7 customer care service',
          'instant payment': 'instant payment',
          'GET STARTED': 'GET STARTED',
          'SKIP': 'SKIP',
          'NEXT': 'NEXT',
          'Welcome Back,': 'Welcome Back,',
          'Investor': 'Investor',
          'Email': 'Email',
          'Email is required': 'Email is required',
          'Password is required': 'Password is required',
          'Password': 'Password',
          'Forgot password?': 'Forgot password?',
          'Please wait': 'Please wait',
          'SIGN IN': 'SIGN IN',
          'SIGN UP': 'SIGN UP',
          'Welcome': 'Welcome',
          "Let's Know you better": "Let's Know you better",
          'First Name is required': 'First Name is required',
          'First Name': 'First Name',
          'Surname is required': 'Surname is required',
          'Surname': 'Surname',
          'Choose Password': 'Choose Password',
          'Comfirm Password is required': 'Comfirm Password is required',
          'Comfirm Password': 'Comfirm Password',
          "Click to accept Cza's ": "Click to accept Cza's ",
          "Terms and Service": "Terms and Service",
          'Balance': 'Balance',
          'Fund Account': 'Fund Account',
          'Withdraw': 'Withdraw',
          'Trading': 'security',
          'Buy & Sell': 'Buy & Sell',
        },

        // german
        'de_DE': {
          'Hello': 'Hallo',
          'welcome to cza exchange': 'Willkommen bei Cza Exchange',
          'high level security': 'hohe Sicherheit',
          'seemless transactions': 'Nahtlose Transaktion',
          '24/7 customer care service': 'Kundendienst rund um die Uhr',
          'instant payment': 'Sofortzahlung',
          'GET STARTED': 'LOSLEGEN',
          'SKIP': 'ÜBERSPRINGEN',
          'NEXT': 'NÄCHSTE',
          'Welcome Back,': 'Willkommen zurück,',
          'Investor': 'Investor',
          'Email': 'Email',
          'Email is required': 'E-Mail ist erforderlich ',
          'Password is required': 'Passwort wird benötigt',
          'Password': 'Passwort',
          'Forgot password?': 'Passwort vergessen?',
          'Please wait': 'Warten Sie mal',
          'SIGN IN': 'ANMELDEN',
          'SIGN UP': 'MELDEN SIE SICH AN',
          'Welcome': 'Willkommen',
          "Let's Know you better": "Lass uns dich besser kennenlernen",
          'First Name is required': 'Vorname ist erforderlich',
          'First Name': 'Vorname',
          'Surname is required': 'Nachname ist erforderlich',
          'Surname': 'Nachname',
          'Choose Password': 'Wählen sie ein Passwort',
          'Comfirm Password is required':
              'Ein Bestätigungspasswort ist erforderlich',
          'Comfirm Password': 'Passwort bestätigen',
          "Click to accept Cza's ":
              "Klicken Sie hier, um Cza's zu akzeptieren ",
          "Terms and Service": "Bedingungen und Service",
          'Balance': 'Balance',
          'Fund Account': 'Fund Account',
          'Withdraw': 'Withdraw',
          'Trading': 'security',
          'Buy & Sell': 'Buy & Sell',
        },
        // spanish
        'es_ES': {
          'Hello': 'Hola',
          'welcome to cza exchange': 'Bienvenida al intercambio de cza',
          'high level security': 'seguridad de alto nivel',
          'seemless transactions': 'transacción aparentemente',
          '24/7 customer care service': 'Servicio de atención al cliente 24/7',
          'instant payment': 'pago instantáneo',
          'GET STARTED': 'EMPEZAR',
          'SKIP': 'SALTAR',
          'NEXT': 'PRÓXIMO',
          'Welcome Back,': 'Bienvenido de nuevo,',
          'Investor': 'Inversor',
          'Email': 'Correo electrónico',
          'Email is required': 'correo electronico es requerido',
          'Password is required': 'se requiere contraseña',
          'Password': 'Contraseña',
          'Forgot password?': 'Has olvidado tu contraseña?',
          'Please wait': 'Espere por favort',
          'SIGN IN': 'INICIAR SESIÓN',
          'SIGN UP': 'INSCRIBIRSE',
          'Welcome': 'Welcome',
          "Let's Know you better": "Let's Know you better",
          'First Name is required': 'First Name is required',
          'First Name': 'First Name',
          'Surname is required': 'Surname is required',
          'Surname': 'Surname',
          'Choose Password': 'Choose Password',
          'Comfirm Password is required': 'Comfirm Password is required',
          'Comfirm Password': 'Comfirm Password',
          "Click to accept Cza's ": "Click to accept Cza's ",
          "Terms and Service": "Terms and Service",
          'Balance': 'Balance',
          'Fund Account': 'Fund Account',
          'Withdraw': 'Withdraw',
          'Trading': 'security',
          'Buy & Sell': 'Buy & Sell',
        },
        // chinese
        'zh_CN': {
          'Hello': '你好',
          'welcome to cza exchange': '欢迎来到 Cza 交易所',
          'high level security': '高级别安全性',
          'seemless transactions': '无缝交易',
          '24/7 customer care service': '24/7 客户关怀服务',
          'instant payment': '即时付款',
          'GET STARTED': '开始吧',
          'SKIP': '跳过',
          'NEXT': '下一个',
          'Welcome Back,': '欢迎回来',
          'Investor': '投资者',
          'Email': '电子邮件',
          'Email is required': '电子邮件为必填项',
          'Password is required': '密码是必需的',
          'Password': '密码',
          'Forgot password?': '忘记密码?',
          'Please wait': '请稍等',
          'SIGN IN': '登入',
          'SIGN UP': '报名',
          'Welcome': '欢迎',
          "Let's Know you better": "让我们更好地了解你",
          'First Name is required': '名字为必填项',
          'First Name': '名',
          'Surname is required': '姓氏为必填项',
          'Surname': '姓',
          'Choose Password': '选择密码',
          'Comfirm Password is required': '需要确认密码',
          'Comfirm Password': '确认密码',
          "Click to accept Cza's ": "点击接受 Cza 的 ",
          "Terms and Service": "条款和服务",
          'Balance': 'Balance',
          'Fund Account': 'Fund Account',
          'Withdraw': 'Withdraw',
          'Trading': 'security',
          'Buy & Sell': 'Buy & Sell',
        }
      };
}
